# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  - group: my-group

steps:
- task: CmdLine@2
  inputs:
    script: 'ls /$(Build.SourcesDirectory)'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  inputs:
    script: 'cat /$(Build.SourcesDirectory)/test.txt'

- task: CmdLine@2
  inputs:
    script: 'sed -i ''s/abc/cba'' /$(Build.SourcesDirectory)/test.txt'

- task: CmdLine@2
  inputs:
    script: 'cat /$(Build.SourcesDirectory)/test.txt'


