// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTracking.Persistence;

namespace VehicleTracking.Persistence.Migrations.Vehicle
{
    [DbContext(typeof(VehicleTrackingDbContext))]
    [Migration("20190202050704_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleTracking.Domain.Entities.AuditLogs", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Action")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EntitiesName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OldData")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UpdatedData")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VehicleTracking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ActivatedCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive");

                    b.Property<string>("RegisteredName")
                        .IsRequired();

                    b.Property<string>("RegisteredPhone")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedCode")
                        .IsUnique();

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("RegisteredPhone")
                        .IsUnique();

                    b.ToTable("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
