// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleTracking.Persistence;

namespace VehicleTracking.Persistence.Migrations.Tracking
{
    [DbContext(typeof(TrackingDbContext))]
    partial class TrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VehicleTracking.Domain.TrackingEntities.TrackingPointSnapshots", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StartPointId")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.Property<string>("VehicleReferencedCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StartPointId")
                        .IsUnique();

                    b.ToTable("TrackingPointSnapshots");
                });

            modelBuilder.Entity("VehicleTracking.Domain.TrackingEntities.TrackingPoints", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 36)))
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedDateTime");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("TrackingPoints");
                });

            modelBuilder.Entity("VehicleTracking.Domain.TrackingEntities.TrackingPoints", b =>
                {
                    b.HasOne("VehicleTracking.Domain.TrackingEntities.TrackingPointSnapshots", "SnapshotPoint")
                        .WithMany("TrackingPoints")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
